import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import "@/styles/index.css";
import { Toaster } from "@/components/ui/sonner";
import { TRPCProvider } from "./trpc/client";
import { HydrationBoundary } from "@tanstack/react-query";
import { ErrorBoundary } from "react-error-boundary";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl='/' >
      <html lang="en">
        <body
        >
          <TRPCProvider>
            <HydrationBoundary>
              <ErrorBoundary fallback={<div>Failed to load form</div>}>
                <Toaster />
                {children}
              </ErrorBoundary>
            </HydrationBoundary>
          </TRPCProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
